import "server-only";

import type {
  CustomerProductActivitySnapshot,
  ProductActivityPortfolioSnapshot,
} from "@/lib/product-activity/types";

const CHECKED_AT = "2026-08-22T14:30:00.000Z";

export const PREVIEW_PRODUCT_ACTIVITY_PORTFOLIO: ProductActivityPortfolioSnapshot = {
  mode: "preview",
  ledgerState: "fresh",
  checkedAt: CHECKED_AT,
  metricVersion: 1,
  autoSyncEnabled: false,
  summary: {
    dau: 7,
    wau: 18,
    mau: 31,
    activeSeconds30: 183_420,
    sessions30: 86,
    completions30: 64,
    internalEvents30: 27,
  },
  products: [
    {
      slug: "virtual-combat-simulator",
      name: "Virtual Combat Simulator",
      firstUsedAt: "2026-01-14T16:04:00.000Z",
      lastUsedAt: "2026-08-22T13:42:00.000Z",
      dau: 4,
      wau: 12,
      mau: 21,
      activeDays30: 24,
      sessions30: 42,
      completions30: 31,
      activeSeconds30: 91_800,
      returnRate30: 67,
      sourceState: "fresh",
      topEvents: [
        { eventType: "encounter_completed", count: 31 },
        { eventType: "initiative_started", count: 29 },
        { eventType: "participant_joined", count: 24 },
      ],
    },
    {
      slug: "gamemastercraft",
      name: "GameMasterCraft",
      firstUsedAt: "2026-01-14T15:28:00.000Z",
      lastUsedAt: "2026-08-21T22:10:00.000Z",
      dau: 3,
      wau: 10,
      mau: 17,
      activeDays30: 20,
      sessions30: 28,
      completions30: 19,
      activeSeconds30: 62_400,
      returnRate30: 59,
      sourceState: "stale",
      topEvents: [
        { eventType: "entity_created", count: 22 },
        { eventType: "encounter_prepared", count: 14 },
        { eventType: "canon_update_confirmed", count: 9 },
      ],
    },
    {
      slug: "mastertyping",
      name: "MasterTyping",
      firstUsedAt: "2026-06-03T18:22:00.000Z",
      lastUsedAt: "2026-08-22T12:12:00.000Z",
      dau: 2,
      wau: 5,
      mau: 8,
      activeDays30: 16,
      sessions30: 16,
      completions30: 14,
      activeSeconds30: 29_220,
      returnRate30: 63,
      sourceState: "rejected",
      topEvents: [
        { eventType: "typing_session_completed", count: 11 },
        { eventType: "assessment_completed", count: 3 },
        { eventType: "mastery_updated", count: 3 },
      ],
    },
  ],
  sources: [
    { key: "vcs", label: "VCS authoritative feed", state: "fresh", environment: "production", lastSuccessfulSyncAt: "2026-08-22T14:28:00.000Z", freshnessLabel: "2 minutes ago", acceptedEvents: 146, rejectedRecords: 0, genuineZeroActivity: false, detail: "Authoritative room events and entity summaries are current." },
    { key: "gmc-family", label: "GMC family authoritative feed", state: "stale", environment: "production", lastSuccessfulSyncAt: "2026-08-22T11:45:00.000Z", freshnessLabel: "2 hours 45 minutes ago", acceptedEvents: 94, rejectedRecords: 0, genuineZeroActivity: false, detail: "The last successful cursor is retained; stale does not mean zero." },
    { key: "mastertyping", label: "MasterTyping operational feed", state: "rejected", environment: "production", lastSuccessfulSyncAt: "2026-08-22T14:20:00.000Z", freshnessLabel: "10 minutes ago", acceptedEvents: 33, rejectedRecords: 2, genuineZeroActivity: false, detail: "Two forbidden or invalid records are quarantined for review." },
    { key: "gravity", label: "Gravity authoritative feed", state: "unavailable", environment: "production", lastSuccessfulSyncAt: null, freshnessLabel: "Never synchronized", acceptedEvents: 0, rejectedRecords: 0, genuineZeroActivity: false, detail: "The source is unavailable; no zero-activity claim is made." },
    { key: "fsg", label: "Four Star General operational feed", state: "disabled", environment: "production", lastSuccessfulSyncAt: null, freshnessLabel: "Disabled", acceptedEvents: 0, rejectedRecords: 0, genuineZeroActivity: false, detail: "Feature-gated until the authenticated product endpoint exists." },
  ],
  recentEvents: [
    { id: "preview-event-1", productSlug: "virtual-combat-simulator", productName: "Virtual Combat Simulator", eventType: "encounter_completed", occurredAt: "2026-08-22T13:42:00.000Z", authorityClass: "server_confirmed", usageContext: "customer", environment: "production", outcome: "succeeded", aggregateType: "battle_room", sourceAggregateId: "room_preview_42", sourceKey: "vcs" },
    { id: "preview-event-2", productSlug: "mastertyping", productName: "MasterTyping", eventType: "typing_session_completed", occurredAt: "2026-08-22T12:12:00.000Z", authorityClass: "client_observed", usageContext: "customer", environment: "production", outcome: "succeeded", aggregateType: "typing_profile", sourceAggregateId: "profile_preview_9", sourceKey: "mastertyping" },
    { id: "preview-event-3", productSlug: "gamemastercraft", productName: "GameMasterCraft", eventType: "encounter_sent_to_vcs", occurredAt: "2026-08-21T22:10:00.000Z", authorityClass: "server_confirmed", usageContext: "internal_test", environment: "production", outcome: "succeeded", aggregateType: "campaign", sourceAggregateId: "campaign_preview_7", sourceKey: "gmc-family" },
  ],
  rejections: [
    { id: "preview-rejection-1", sourceKey: "mastertyping", code: "forbidden_field", summary: "A record contained a field outside the scalar allowlist.", rejectedAt: "2026-08-22T14:20:00.000Z", fingerprint: "a1f9d0d6429d" },
    { id: "preview-rejection-2", sourceKey: "mastertyping", code: "identity_link_failure", summary: "The stable Supabase identity has not been explicitly linked to an Operations customer.", rejectedAt: "2026-08-22T14:19:00.000Z", fingerprint: "c9b72d56ee1f" },
  ],
  message: "Synthetic certification data demonstrates fresh, stale, unavailable, disabled, rejected, and genuine source states without contacting a product app.",
};

export const PREVIEW_CUSTOMER_PRODUCT_ACTIVITY: CustomerProductActivitySnapshot = {
  mode: "preview",
  state: "fresh",
  databaseCustomerId: null,
  products: [
    {
      slug: "virtual-combat-simulator",
      name: "Virtual Combat Simulator",
      firstUsedAt: "2026-01-14T16:04:00.000Z",
      lastUsedAt: "2026-08-22T13:42:00.000Z",
      activeDays7: 3,
      activeDays30: 9,
      activeDays90: 21,
      sessions30: 12,
      completions30: 9,
      activeSeconds30: 31_820,
      sourceState: "fresh",
      sourceKey: "vcs",
      authorityClasses: ["server_confirmed"],
      entities: [
        { id: "preview-room-1", aggregateType: "battle_room", displayLabel: "The Ashen Vault", status: "active", createdAt: "2026-01-14T16:04:00.000Z", lastMeaningfulActivityAt: "2026-08-22T13:42:00.000Z", counters: { participant_count: 5, encounter_count: 12, round_count: 86, action_count: 344 }, sourceUrl: "https://vcs.example.test/rooms/room_preview_42", authorityClass: "server_confirmed" },
      ],
    },
    {
      slug: "gamemastercraft",
      name: "GameMasterCraft",
      firstUsedAt: "2026-01-14T15:28:00.000Z",
      lastUsedAt: "2026-08-21T22:10:00.000Z",
      activeDays7: 2,
      activeDays30: 7,
      activeDays90: 18,
      sessions30: 8,
      completions30: 6,
      activeSeconds30: 19_420,
      sourceState: "stale",
      sourceKey: "gmc-family",
      authorityClasses: ["server_confirmed"],
      entities: [
        { id: "preview-campaign-1", aggregateType: "campaign", displayLabel: "Embers of Karth", status: "active", createdAt: "2026-01-14T15:28:00.000Z", lastMeaningfulActivityAt: "2026-08-21T22:10:00.000Z", counters: { session_count: 18, entity_count: 46, encounter_count: 12 }, sourceUrl: "https://gmc.example.test/campaigns/campaign_preview_7", authorityClass: "server_confirmed" },
      ],
    },
  ],
  timeline: PREVIEW_PRODUCT_ACTIVITY_PORTFOLIO.recentEvents.slice(0, 2),
  message: "Owner-only synthetic activity. Names shown here are private summaries and are never forwarded to third-party analytics.",
};
